services:
  stalwart-mail:
    image: stalwartlabs/stalwart:latest-alpine # for production choose specific version from https://hub.docker.com/r/stalwartlabs/stalwart/tags
    ports:
      - "25" # SMTP
      #- "110:110"    # POP3 (insecure)
      #- "143:143"    # IMAP (insecure)
      #- "449:443"    # HTTPS (no use in Dokploy)
      - "465" # SMTPS  (deprecated, but often required)
      - "587" # Submission
      - "993" # IMAPS
      - "995" # POP3S
      - "4190" # ManageSieve
      - "8080" # HTTP API
    volumes:
      - stalwart_data_new:/opt/stalwart-mail
      - certs:/data/certs:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  traefik-certs-dumper:
    image: ghcr.io/kereis/traefik-certs-dumper:latest
    container_name: traefik-certs-dumper
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/dokploy/traefik/dynamic:/traefik:ro
      - certs:/output
volumes:
  certs:
  stalwart_data_new:
